requires = ["tox>=4"]
env_list = ["lint", "3.13", "3.12", "3.11", "3.10"]

[env_run_base]
description = "run unit tests"
deps = ["pytest"]
commands = [
    ["pytest", { replace = "posargs", default = ["tests"], extend = true }],
]

[env.lint]
description = "run linter and formatter"
skip_install = true
deps = [ "pre-commit", "ruff"]
commands = [
    ["pre-commit", "run", "--all-files"],
    ["ruff", "check", { replace = "posargs", default = ["."], extend = true }],
    ["ruff", "format", { replace = "posargs", default = ["."], extend = true }],
]

[gh.python]
"3.13" = ["3.13", "lint"]
"3.12" = ["3.12"]
"3.11" = ["3.11"]
"3.10" = ["3.10"]
