name: release
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
  workflow_run:
    workflows:
      - check
    types:
      - completed

jobs:
  build-and-publish:
    name: Build package
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
      - name: Set up Python
        run: uv python install
      - name: Build package
        run: uv build
      - name: Publish package
        run: uv publish
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  github-release:
    name: Create release on GitHub
    runs-on: ubuntu-latest
    needs:
      - build-and-publish
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} dist/* --title ${{ github.ref_name }}
